Write-Host "LOCALAPPDATA:     $env:LOCALAPPDATA"
Write-Host "ANDROID_HOME:     '$env:ANDROID_HOME'"
Write-Host "ANDROID_SDK_ROOT: '$env:ANDROID_SDK_ROOT'"
Write-Host ""
$guess = "$env:LOCALAPPDATA\Android\Sdk"
Write-Host "Probando: $guess"
Write-Host "Existe: $(Test-Path $guess)"
